jobs:

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true

  - script: |
      sudo apt -q update > /dev/null
      sudo apt -yq install gfortran > /dev/null
    displayName: install Gfortran
  - script: pip install flake8 mypy
    displayName: 'install Python dev tools'
  - script: |
      flake8
      mypy .
    displayName: 'PEP8, Type Check'
  - script: python setup_spacepy.py
    displayName: 'Install SpacePy and Test CDF Read'


# - job: MacOS_CMake
  # pool:
    # vmImage: macOS-latest

  # steps:
  # - task: UsePythonVersion@0
    # inputs:
      # versionSpec: '3.6'
      # addToPath: true
  # - script: brew install gcc
    # displayName: install compilers
  # - script: python setup_spacepy.py
    # displayName: 'Install SpacePy and Test CDF Read'