name: ci

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install packages
      run: sudo apt install -yq --no-install-recommends gfortran
    - name: Install test dependencies
      run: pip install flake8 mypy
    - name: Lint
      run: flake8
    - name: Type check
      run: mypy .
    - name: install spacepy
      run: python setup_spacepy.py
